version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/1-simple-hello-world
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/2-simple-hello-world-to-a-redirect
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/3-showing-a-searchable-list-of-contacts
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/4-adding-a-new-contact
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/5-viewing-the-details-of-a-contact
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/6-editing-a-contact
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-3/7-deleting-a-contact
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/1-installing-htmx-third-party
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/2-triggering-http-requests
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/3-htmx-vs-plain-html-responses
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/4-targeting-other-elements
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/5-swap-styles
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/6-using-events-mouseenter
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/7-using-events-click-and-keyup
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/8-passing-request-parameters-enclosing-forms
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/9-passing-request-parameters-including-inputs
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-4/10-passing-request-parameters-inline-values
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-4/11-history-support
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-5/1-installing-htmx-vendored
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: /chapter-5/2-adding-hx-boost-to-contact-app
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/3-a-second-step-deleting-contacts-with-http-delete
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/4-next-steps-validating-contact-emails-update-our-input-type
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/5-next-steps-validating-contact-emails-inline-validation
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/6-next-steps-validating-contact-emails-validating-emails-server-side
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/7-next-steps-validating-contact-emails-taking-the-user-experience-further
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/8-next-steps-validating-contact-emails-debouncing-our-validation-requests
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/9-next-steps-validating-contact-emails-ignoring-non-mutating-keys
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/10-another-application-improvement-paging-adding-paging-widgets
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/11-another-application-improvement-paging-click-to-load
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-5/12-another-application-improvement-paging-infinite-scroll
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/1-adding-active-search
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/2-targeting-the-correct-element
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/3-paring-down-our-content
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/4-http-headers-in-htmx
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/5-updating-the-navigation-bar-with-hx-push-url
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
  - package-ecosystem: pip
    directory: chapter-6/6-adding-a-request-indicator
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
