name: Tests

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          "chapter-3/1-simple-hello-world",
          "chapter-3/2-simple-hello-world-to-a-redirect",
          "chapter-3/3-showing-a-searchable-list-of-contacts",
          "chapter-3/4-adding-a-new-contact",
          "chapter-3/5-viewing-the-details-of-a-contact",
          "chapter-3/6-editing-a-contact",
          "chapter-3/7-deleting-a-contact",
          "chapter-4/1-installing-htmx-third-party",
          "chapter-4/2-triggering-http-requests"
        ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: ${{matrix.example}}
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: ${{matrix.example}}
        run: python3 -m pytest
