name: Type Checker

on:
  push:

jobs:
  type_checker:
    name: Type Checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          "chapter-3/1-simple-hello-world",
          "chapter-3/2-simple-hello-world-to-a-redirect",
          "chapter-3/3-showing-a-searchable-list-of-contacts",
          "chapter-3/4-adding-a-new-contact",
          "chapter-3/5-viewing-the-details-of-a-contact",
          "chapter-3/6-editing-a-contact",
          "chapter-3/7-deleting-a-contact",
          "chapter-4/1-installing-htmx-third-party",
          "chapter-4/2-triggering-http-requests",
          "chapter-4/3-htmx-vs-plain-html-responses",
          "chapter-4/4-targeting-other-elements",
          "chapter-4/5-swap-styles",
          "chapter-4/6-using-events-mouseenter",
          "chapter-4/7-using-events-click-and-keyup",
          "chapter-4/8-passing-request-parameters-enclosing-forms",
          "chapter-4/9-passing-request-parameters-including-inputs",
          "chapter-4/10-passing-request-parameters-inline-values",
          "chapter-4/11-history-support",
          "chapter-5/1-installing-htmx-vendored",
          "chapter-5/2-adding-hx-boost-to-contact-app"
        ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: ${{matrix.example}}
        run: |
          pip install -r requirements.txt
          python3 -m pip install mypy 

      - name: Type Checker
        working-directory: ${{matrix.example}}
        run: mypy .
